<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please enter a valid email address (Ex johndoedomain.com)</name>
   <tag></tag>
   <elementGuidId>2f7d5eed-6a8f-44ee-98ad-1469b2852a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>deb6570f-80d5-4103-aa3a-8793a3bf6180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>369b8ea5-3e6a-4e64-884c-a0c7ffe174c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34ac6df4-a2ea-4518-bedc-23d78bbc5345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mage-error</value>
      <webElementGuid>0dabec90-adae-4740-b8f8-25ea89018d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-error</value>
      <webElementGuid>2699c1cc-becc-4310-80f8-ec94690b47cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a valid email address (Ex: johndoe@domain.com).</value>
      <webElementGuid>858cba77-27fa-4ddc-a8aa-3ab2ab7a3e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-error&quot;)</value>
      <webElementGuid>249d7cca-d22e-40bc-a84b-ed87dda9adc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='email-error']</value>
      <webElementGuid>4fae7fe3-ddbf-41c5-91b1-87a348a68bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/div[2]/div/div</value>
      <webElementGuid>393a2bdb-9613-409c-9246-c2f7c527761f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[2]</value>
      <webElementGuid>90a5b990-3b42-4eb3-8ba7-4fe0fff85f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you have an account, sign in with your email address.'])[1]/following::div[3]</value>
      <webElementGuid>1090f804-41a5-4059-b970-8d4cc8a6a13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::div[1]</value>
      <webElementGuid>40e69618-4b3b-4182-b628-173d638414ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a required field.'])[1]/preceding::div[1]</value>
      <webElementGuid>9a6c1d15-4900-4561-96fd-f6f65321b2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter a valid email address (Ex: johndoe@domain.com).']/parent::*</value>
      <webElementGuid>37b7bdb9-51aa-422a-85e4-25dbff847bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div</value>
      <webElementGuid>25a2fb76-4030-47cf-8685-9d333cc1c8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'email-error' and (text() = 'Please enter a valid email address (Ex: johndoe@domain.com).' or . = 'Please enter a valid email address (Ex: johndoe@domain.com).')]</value>
      <webElementGuid>0d595131-9c91-476f-98db-a556f4de42d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
